
pairs = [
    ['my name is (.*)', ['Hi %1!']],
    ['(hi|hello|hey)', ['Hello!', 'Hi there!']],
    ['what can you do', ['I can chat with you!']],
    ['quit', ['Bye-bye!', 'See you later!']],
    ['(help|assist) me', ['Sure, I am here to help.']],
    ['what (can|do) you (do|offer)', ['I can chat, answer questions, and more!']],
    ['good (morning|afternoon|evening)', ['Good %1!']],
    ['(bye|goodbye|see you)', ['Goodbye!', 'Take care!', 'See you soon!']],
    ['what is your name', ['I am a chatbot created to help you.']],
    ['who are you', ['I am a simple rule-based chatbot.']],
    ['(.*) your favorite color', ['I like all colors equally!']],
    ['how is the weather', ['I’m not sure, I live in the cloud ☁️']],
    ['are you happy', ['I’m just code, but I love talking to you!']],
    ['(.*) your hobby', ['Chatting with people like you.']],
    ['my name is (.*)', ['Nice to meet you, %1!']],
    ['(hi|hello|hey|hii|heyy)', ['Hello!', 'Hi there!', 'Hey!', 'Greetings!']],
    ['good (morning|afternoon|evening)', ['Good %1 to you too!']],
    ['howdy', ['Howdy partner!']],
    ['(bye|goodbye|see you|see ya)', ['Bye!', 'Goodbye!', 'See you later!', 'Take care!']],
    ['(exit|quit)', ['Goodbye! Type again if you need anything.', 'Session ended.']],
    ['how are you', ['I’m doing great, thanks! How about you?']],
    ['(i am|i\'m) (fine|good|okay|not good|sad|happy)', ['Glad to hear that!', 'Oh, I hope you feel better soon.']],
    ['what is your name', ['My name is ChatBot, your assistant!']],
    ['who are you', ['I am a rule-based chatbot created to talk with you.']],
    ['are you real', ['I’m virtual, but I’m here for you!']],
    ['(help|assist) me', ['Sure! I’ll do my best. What do you need help with?']],
    ['can you help me with (.*)', ['I can try to help with %1. What exactly do you need?']],
    ['tell me a joke', ['Why don’t scientists trust atoms? Because they make up everything!', 'Why was the math book sad? It had too many problems.']],
    ['make me laugh', ['I would, but I only know bad jokes 😅']],
    ['i feel (sad|down|upset)', ['I’m sorry to hear that. I’m here for you.']],
    ['i feel (happy|good|great)', ['That’s wonderful to hear!']],
    ['i\'m bored', ['Let’s chat! Or I can tell you a joke.']],
    ['what time is it', ['I’m not wearing a watch 😄, but your system clock knows!']],
    ['what day is it', ['Check your calendar, but I think it’s a great day!']],
    ['do you like (.*)', ['I don’t have preferences, but %1 sounds interesting!']],
    ['i like (.*)', ['Cool! %1 is nice.']],
    ['i hate (.*)', ['Oh no! Why do you hate %1?']],
    ['are you single', ['Haha! I’m committed to chatting with you 😄']],
    ['do you have a girlfriend', ['Nope, I’m just a bunch of code!']],
    ['do you sleep', ['Nope, I’m always awake for you.']],
    ['where do you live', ['I live in your device – or maybe in the cloud!']],
    ['how old are you', ['I was created recently, but I’m learning fast!']],
    ['what is life', ['42! Just kidding. It’s what you make of it.']],
    ['do you believe in god', ['I don’t have beliefs, but many people do.']],
    ['do you know me', ['I’m getting to know you more each time we chat!']],
    ['(thank you|thanks)', ['You’re welcome!', 'Anytime!', 'Glad to help!']],
    ['thanks a lot', ['It’s my pleasure!']],
    ['(.*)', ['Interesting...', 'Tell me more.', 'Why do you say that?', 'Let’s talk about something else.']]
]


chatbot = Chat(pairs, reflections)